Добавлено техническое задание
dorofeeva130/Harry-Potter pull request #8
Opened 2024-12-16 08:27 UTC by dorofeeva130

2024-12-19 07:41 UTC, Laggon requested changes
Нужно указать участников команды, как минимум Фамилию и Имя, а также логин GitHub

Также запросить ревью у остальных участников команды

2024-12-19 10:37 UTC, Laggon requested changes
Участников указать в файле `README.md`

Второй участник должен отправить ревью, Approve или Request changes

2024-12-19 10:38 UTC, Laggon commented
Для 3-х спринтов должна быть задача для каждого участника

2024-12-23 07:09 UTC, Laggon approved these changes

2024-12-23 07:10 UTC, Ann7750 approved these changes

2024-12-23 07:19 UTC, merged