Интерфейс приложения
dorofeeva130/Harry-Potter pull request #9
Opened 2024-12-16 10:46 UTC by dorofeeva130

2024-12-19 07:37 UTC, Laggon requested changes
Сначала нужно утвердить техническое задание

2024-12-23 07:11 UTC, Ann7750 approved these changes

2024-12-23 07:22 UTC, Laggon requested changes
Нужно выполнить слияние из основной ветки, чтобы не было отставания и конфликтов

Файлы сайтов обычно хранят в папках путь, которых написан латинскими буквами без пробелов (допускается дефис)

2024-12-23 07:22 UTC, Laggon commented
Нужно указать связанную задачу в блоке Development

2024-12-23 07:39 UTC, Laggon approved these changes

2024-12-23 07:39 UTC, merged